blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/voyvodka/webhook-engine/discussions
    about: Ask and answer questions in GitHub Discussions.
