// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebhookEngine.Infrastructure.Data;

#nullable disable

namespace WebhookEngine.Infrastructure.Migrations
{
    [DbContext(typeof(WebhookDbContext))]
    [Migration("20260505140607_AddIdempotencyUniqueIndex")]
    partial class AddIdempotencyUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebhookEngine.Core.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("api_key_hash");

                    b.Property<string>("ApiKeyPrefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("api_key_prefix");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("IdempotencyWindowMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1440)
                        .HasColumnName("idempotency_window_minutes");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("RetryPolicyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("retry_policy");

                    b.Property<string>("SigningSecret")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("signing_secret");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyPrefix")
                        .IsUnique();

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("WebhookEngine.Core.Entities.DashboardUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("admin")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("dashboard_users", (string)null);
                });

            modelBuilder.Entity("WebhookEngine.Core.Entities.Endpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CustomHeadersJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_headers")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("SecretOverride")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("secret_override");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<bool>("TransformEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("transform_enabled");

                    b.Property<string>("TransformExpression")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("transform_expression");

                    b.Property<DateTime?>("TransformValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transform_validated_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .HasDatabaseName("idx_endpoints_app_id");

                    b.HasIndex("AppId", "Status")
                        .HasDatabaseName("idx_endpoints_status");

                    b.ToTable("endpoints", (string)null);
                });

            modelBuilder.Entity("WebhookEngine.Core.Entities.EndpointHealth", b =>
                {
                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.Property<string>("CircuitState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Closed")
                        .HasColumnName("circuit_state");

                    b.Property<int>("ConsecutiveFailures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("consecutive_failures");

                    b.Property<DateTime?>("CooldownUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cooldown_until");

                    b.Property<DateTime?>("LastFailureAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_failure_at");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("EndpointId");

                    b.ToTable("endpoint_health", (string)null);
                });

            modelBuilder.Entity("WebhookEngine.Core.Entities.EventType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SchemaJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("schema_json");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .HasDatabaseName("idx_event_types_app_id");

                    b.HasIndex("AppId", "Name")
                        .IsUnique();

                    b.ToTable("event_types", (string)null);
                });

            modelBuilder.Entity("WebhookEngine.Core.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.Property<string>("EventId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_id");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_type_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("locked_by");

                    b.Property<int>("MaxRetries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(7)
                        .HasColumnName("max_retries");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("ScheduledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("LockedAt")
                        .HasDatabaseName("idx_messages_stale_locks")
                        .HasFilter("status = 'Sending' AND locked_at IS NOT NULL");

                    b.HasIndex("ScheduledAt")
                        .HasDatabaseName("idx_messages_queue")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("AppId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_messages_created_at");

                    b.HasIndex("AppId", "EndpointId")
                        .HasDatabaseName("idx_messages_app_endpoint");

                    b.HasIndex("AppId", "EventTypeId")
                        .HasDatabaseName("idx_messages_app_event_type");

                    b.HasIndex("AppId", "IdempotencyKey")
                        .HasDatabaseName("idx_messages_app_idempotency")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("AppId", "Status")
                        .HasDatabaseName("idx_messages_app_status");

                    b.HasIndex("AppId", "EndpointId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("idx_messages_app_endpoint_idempotency")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("WebhookEngine.Core.Entities.MessageAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("RequestHeadersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_headers");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("idx_attempts_message_id");

                    b.HasIndex("EndpointId", "Status", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("idx_attempts_endpoint_status");

                    b.ToTable("message_attempts", (string)null);
                });

            modelBuilder.Entity("endpoint_event_types", b =>
                {
                    b.Property<Guid>("endpoint_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("event_type_id")
                        .HasColumnType("uuid");

                    b.HasKey("endpoint_id", "event_type_id");

                    b.HasIndex("event_type_id");

                    b.ToTable("endpoint_event_types");
                });

            modelBuilder.Entity("WebhookEngine.Core.Entities.Endpoint", b =>
                {
                    b.HasOne("WebhookEngine.Core.Entities.Application", "Application")
                        .WithMany("Endpoints")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("WebhookEngine.Core.Entities.EndpointHealth", b =>
                {
                    b.HasOne("WebhookEngine.Core.Entities.Endpoint", "Endpoint")
                        .WithOne("Health")
                        .HasForeignKey("WebhookEngine.Core.Entities.EndpointHealth", "EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("WebhookEngine.Core.Entities.EventType", b =>
                {
                    b.HasOne("WebhookEngine.Core.Entities.Application", "Application")
                        .WithMany("EventTypes")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("WebhookEngine.Core.Entities.Message", b =>
                {
                    b.HasOne("WebhookEngine.Core.Entities.Application", "Application")
                        .WithMany("Messages")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebhookEngine.Core.Entities.Endpoint", "Endpoint")
                        .WithMany("Messages")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebhookEngine.Core.Entities.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Endpoint");

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("WebhookEngine.Core.Entities.MessageAttempt", b =>
                {
                    b.HasOne("WebhookEngine.Core.Entities.Endpoint", "Endpoint")
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebhookEngine.Core.Entities.Message", "Message")
                        .WithMany("Attempts")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("endpoint_event_types", b =>
                {
                    b.HasOne("WebhookEngine.Core.Entities.Endpoint", null)
                        .WithMany()
                        .HasForeignKey("endpoint_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebhookEngine.Core.Entities.EventType", null)
                        .WithMany()
                        .HasForeignKey("event_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebhookEngine.Core.Entities.Application", b =>
                {
                    b.Navigation("Endpoints");

                    b.Navigation("EventTypes");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("WebhookEngine.Core.Entities.Endpoint", b =>
                {
                    b.Navigation("Health");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("WebhookEngine.Core.Entities.Message", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
